### ISSUE TITLE
Email adresses not meeting standard format criteria

### ISSUE THREAD

**Issue by P1etroo** [flofriday/VSUE-Testsuite#2]
Although valid, all costant fake adresses like therecipientserver@doesnotexist disregard the recommendation of ICANN (https://www.icann.org/en/announcements/details/new-gtld-dotless-domain-names-prohibited-30-8-2013-en) and can easily lead to messages being invalid if a regex check is made on the transfer server. Appending ".com" will reduce the number of validation problems

**Comment by flofriday** [comment]
I see your point, just as a rough estimate you should probably not use regex to validate emails ([blog post why](https://www.netmeister.org/blog/email.html)). In general the only real way to validate an email address is to just send an email and let them click a link etc.

I know that's out of the scope for VSUE, but I just wanted to say that.

**Comment by flofriday** [comment]
Can you checkout #3 and tell me if that fixes your issues?
